const Router = require('express').Router()
const UserRouter = require('./UserRouter.js')
// const MilestoneRouter = require('./MilestoneRouter.js')
// const JournalRouter = require('./JournalRouter.js')
// const ItemRouter = require('./ItemRouter.js')
// const QuestRouter = require('./QuestRouter')
Router.use('/users', UserRouter)
// Router.use('/milestones', MilestoneRouter)
// Router.use('/entries', JournalRouter)
// Router.use('/items', ItemRouter)
// Router.use('/quests', QuestRouter)
module.exports = Router