const Router = require('express').Router()
const UserRouter = require('./UserRouter.js')
const MilestoneRouter = require('./MilestoneRouter.js')
const JournalRouter = require('./JournalRouter.js')
const ItemRouter = require('./ItemRouter.js')
const QuestRouter = require('./QuestRouter')
const SkillRouter = require('./SkillRouter')
Router.use('/users', UserRouter)
Router.use('/milestones', MilestoneRouter)
Router.use('/entries', JournalRouter)
Router.use('/items', ItemRouter)
Router.use('/quests', QuestRouter)
Router.use('/skills', SkillRouter)
module.exports = Router